sudo: required

language: ruby

services:
  - docker

before_install:
  - docker build -t katsyoshi/itamae-plugin-recipe-pyenv .

script:
  - docker run -t katsyoshi/itamae-plugin-recipe-pyenv bundle exec rake
